# Generated by Django 3.0.5 on 2020-09-21 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='images/')),
                ('address', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('department', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Orthopaedic', 'Orthopaedic'), ('Dentist', 'Dentist'), ('Medicine', 'Medicine'), ('Emergency', 'Emergency'), ('Neurologist', 'Neurologist')], default='Emergency', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
